# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gophersay < Formula
  desc ""
  homepage "https://github.com/oclmod/homebrew-tools.git"
  version "1.0.57"

  on_macos do
    on_intel do
      url "https://github.com/oclmod/gophersay/releases/download/v1.0.57/gophersay_Darwin_x86_64.tar.gz"
      sha256 "131a40382c92ff0653a419c4e1e190e3dd9dcb47bebc56170e0d14846f3a51da"

      def install
        bin.install "gophersay"
      end
    end
    on_arm do
      url "https://github.com/oclmod/gophersay/releases/download/v1.0.57/gophersay_Darwin_arm64.tar.gz"
      sha256 "f9b9c5f49af8525506b1f3f59d6da541a47112b8a34b953b6f8a0352c64afa67"

      def install
        bin.install "gophersay"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oclmod/gophersay/releases/download/v1.0.57/gophersay_Linux_x86_64.tar.gz"
        sha256 "95de5881e5ce8b3573dee845b8b5811931f9155519b6d029f1ff47f95260b0d6"

        def install
          bin.install "gophersay"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oclmod/gophersay/releases/download/v1.0.57/gophersay_Linux_arm64.tar.gz"
        sha256 "5b1d6a594cdcc8bf3920a1c9141370483071d10a44f6ce5141f8ccded0b01100"

        def install
          bin.install "gophersay"
        end
      end
    end
  end
end
